apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "boilerplate-nestjs-api.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "boilerplate-nestjs-api.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
