{{- $hasSecrets := false -}}
{{- range $k, $v := .Values.secret -}}
  {{- if $v -}}
    {{- $hasSecrets = true -}}
  {{- end -}}
{{- end -}}
{{- if $hasSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "boilerplate-nestjs-api.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "boilerplate-nestjs-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
